### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by jankeesvw** [PatchworkBoy/homebridge-edomoticz#137]
I'm not sure what happend, but I'm using homebridge-edomoticz with this docker Docker container https://hub.docker.com/r/marcoraddatz/homebridge/tags/ and suddenly I get this stack trace when booting (the stacktrace is in reverse order)

```
    at Object.Module._extensions..js (module.js:565:10)
    at Module._compile (module.js:556:32)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:8)
    at Server._configCachedPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:339:24)
    at Object.configureAccessory (/usr/lib/node_modules/homebridge-edomoticz/index.js:247:21)
    at Object.eDomoticzAccessory (/usr/lib/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:75:10)
    at Object.publishServices (/usr/lib/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:83:29)
    at Object.getServices (/usr/lib/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:1622:84)
TypeError: Cannot read property 'on' of undefined
```

**Comment by PatchworkBoy** [comment]
What version of homebridge? (look for the "_id": field in /usr/local/lib/node_modules/homebridge-edomoticz/package.json)

Stop homebridge,
Run with `DEBUG=* homebridge -D` and wait for it to crash, and get the last message received prior to crashing.

**Comment by jankeesvw** [comment]
I noticed that `domoticz_accessory.js:1622` is related to the rain sensor, I tried to disable my weather sensor but that didn't solve the problem unfortunately.

**Comment by jankeesvw** [comment]
It's fetching the latest version on boot, and the line number matches so I guess it's the lastest version.

**Comment by PatchworkBoy** [comment]
When did you last boot? There have been 4 version updates today.

**Comment by jankeesvw** [comment]
A second ago, is version 2.1.10 the latest?

**Comment by jankeesvw** [comment]
I should probably also lock a version instead of picking the latest every boot...

**Comment by PatchworkBoy** [comment]
It is, yes. A UUID has changed for that service on this boot and can’t updated your cached accessory correctly (because the cache tries to match on UUID). Remove ~/.homebridge/accessories/cachedAccessories and restart homebridge and it should hopefully rebuild the cache again. 

If that doesn’t work, remove ~/.homebridge/accessories and ~/.homebridge/persist, remove the bridge from your home & re-add.

**Comment by jankeesvw** [comment]
I’ll try that tomorrow, thanks! I’ll close this issue if it works!

**Comment by jankeesvw** [comment]
Yes it works again! But I had to re add all the Domoticz devices in Homekit.
