### ISSUE TITLE
Plugin does not start after latest upgrade

### ISSUE THREAD

**Issue by RienduPre** [PatchworkBoy/homebridge-edomoticz#196]
I updated to the latest version v2.1.28 and after the restart of Homebridge I get this error.

[2/9/2020, 10:47:12 AM] TypeError: Cannot read property 'name' of undefined
    at eDomoticzPlatform.<anonymous> (/homebridge/node_modules/homebridge-edomoticz/index.js:196:90)
    at Request._callback (/homebridge/node_modules/homebridge-edomoticz/lib/domoticz.js:87:9)
    at Request.self.callback (/homebridge/node_modules/homebridge-edomoticz/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-edomoticz/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-edomoticz/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)

Any idea what might cause this ?

**Comment by PatchworkBoy** [comment]
Have just pushed 2.1.29 to npmjs...

remove cachedAccessories file (usually `rm -rf ~/.homebridge/accessories/cachedAccessories`), update and restart.

**Comment by RienduPre** [comment]
Solved, thanks....
