### ISSUE TITLE
Problems with last homebridge beta

### ISSUE THREAD

**Issue by macjl** [PatchworkBoy/homebridge-edomoticz#203]
Hello,

As you can see in this [issue](https://github.com/homebridge/homebridge/issues/2459#issuecomment-613328752), there are problems with homebridge-edomoticz with last homebridge beta.

Can it be fixed?

Here are what I see in logs in beta 38:

```
[4/14/2020, 11:13:46 AM] Loaded config.json with 0 accessories and 1 platforms.
[4/14/2020, 11:13:46 AM] ---
[4/14/2020, 11:13:47 AM] Loaded plugin: homebridge-edomoticz
[4/14/2020, 11:13:47 AM] ====================
[4/14/2020, 11:13:47 AM] ERROR INITIALIZING PLUGIN homebridge-edomoticz:
[4/14/2020, 11:13:47 AM] TypeError: Cannot read property 'adminOnlyAccess' of undefined
    at Characteristic.get [as accessRestrictedToAdmins] (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:429:21)
    at Function.Helper.fixInheritance (/opt/node_modules/homebridge-edomoticz/lib/helper.js:65:39)
    at Plugin.module.exports [as pluginInitializer] (/opt/node_modules/homebridge-edomoticz/index.js:51:12)
    at Plugin.initialize (/opt/node/lib/node_modules/homebridge/src/plugin.ts:164:10)
    at /opt/node/lib/node_modules/homebridge/src/pluginManager.ts:134:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/opt/node/lib/node_modules/homebridge/src/pluginManager.ts:117:18)
    at Server.start (/opt/node/lib/node_modules/homebridge/src/server.ts:144:24)
    at cli (/opt/node/lib/node_modules/homebridge/src/cli.ts:76:10)
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge/bin/homebridge:17:22)
```

and in beta 39 : 

```
[4/14/2020, 8:14:01 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/14/2020, 8:14:01 PM] ---
[4/14/2020, 8:14:02 PM] Loaded plugin: homebridge-edomoticz
[4/14/2020, 8:14:02 PM] ====================
[4/14/2020, 8:14:02 PM] ERROR INITIALIZING PLUGIN homebridge-edomoticz:
[4/14/2020, 8:14:02 PM] TypeError: this.setProps is not a function
    at Characteristic.set [as accessRestrictedToAdmins] (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:419:10)
    at Function.Helper.fixInheritance (/opt/node_modules/homebridge-edomoticz/lib/helper.js:65:32)
    at Plugin.module.exports [as pluginInitializer] (/opt/node_modules/homebridge-edomoticz/index.js:51:12)
    at Plugin.initialize (/opt/node/lib/node_modules/homebridge/src/plugin.ts:164:10)
    at /opt/node/lib/node_modules/homebridge/src/pluginManager.ts:134:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/opt/node/lib/node_modules/homebridge/src/pluginManager.ts:117:18)
    at Server.start (/opt/node/lib/node_modules/homebridge/src/server.ts:144:24)
    at cli (/opt/node/lib/node_modules/homebridge/src/cli.ts:76:10)
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge/bin/homebridge:17:22)
```

**Comment by PatchworkBoy** [comment]
Nothing I can do in the short-term... am a key worker so flat out with more urgent things at the mo. Will address once all this *wafts hands in air* is over with... (if anyone else fancies tackling in meantime - feel free)

**Comment by macjl** [comment]
Closing — this was specific to Homebridge beta versions from 2020. Homebridge v2 compatibility issues have been addressed in subsequent releases. Thanks for the plugin!
