### ISSUE TITLE
homebridge 2.0 compatibility

### ISSUE THREAD

**Issue by akamming** [PatchworkBoy/homebridge-edomoticz#285]
Hi,

happy edomoticz user here..

I just upgraded homebridge from an older version (don't know which one) to 1.8.4 on and noticed it now gives a warning on edomoticz:

```
homebridge-edomoticz might not be ready for Homebridge v2.0
The developer has not specifically marked your installed version of the plugin as compatible with Homebridge v2.0, but it may still work.
```
with a link to [https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0)

I don't know when HB will switch to 2.0, but i did notice breaking changes in their APIs ( I also maintain a small homebridge plugin and had to change a few tiny things) so i wanted to bring this to your attention..

**Comment by acaonweb** [comment]
Up

**Comment by PatchworkBoy** [comment]
Aware. When I get round to it / someone else does and sends me a pull request.

**Comment by acaonweb** [comment]
Ok, happy to know.
Thanx for the new.

Best wishes for a Merry Christmas and a Happy New Year

Fabrizio

--
Visita http://www.acaonweb.it
Il 23 dic 2024, 10:22 +0100, Marci ***@***.***>, ha scritto:

**Comment by vespino** [comment]
Any update on this? Don’t know when version 2.0 of Homebridge will be released, but do hope to keep my existing setup running. Cheers.

**Comment by PatchworkBoy** [comment]
No.

**Comment by vespino** [comment]
I have no idea how to go about this, or else I would be glad to help. I’ve only started doing a bit of Python myself recently, so this is probably still a bit too difficult for me.

**Comment by vespino** [comment]
Errors I'm getting when testing Homebridge v2.0.0-beta.23:

```
[1/12/2025, 8:47:54 AM] [Domoticz] Device: Computer (458)

/homebridge/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:89
        this.platformAccessory.category = Categories.TELEVISION;
                                                     ^
TypeError: Cannot read properties of undefined (reading 'TELEVISION')
    at new eDomoticzAccessory (/homebridge/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:89:54)
    at eDomoticzPlatform.<anonymous> (/homebridge/node_modules/homebridge-edomoticz/index.js:170:37)
    at Request._callback (/homebridge/node_modules/homebridge-edomoticz/lib/domoticz.js:88:9)
    at Request.self.callback (/homebridge/node_modules/homebridge-edomoticz/node_modules/request/request.js:185:22)
    at Request.emit (node:events:524:28)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-edomoticz/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:524:28)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-edomoticz/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:638:28)
    at IncomingMessage.emit (node:events:536:35)
[1/12/2025, 8:47:54 AM] [Domoticz] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.
```

These all concern manually created dummy devices set to media player. After temporarily excluding these devices, all seems to be running fine.

Maybe it's useful.

**Comment by vespino** [comment]
Any update as HB is getting closer and closer to v2.0?

**Comment by Anderson69s** [comment]
Hi, I hope everyone is ok.

I'm starting to have some real warning from homebridge & Edomoticz... Homebridge V1 to V2 looks really big, I'm afraid we can't use this cool software anymore...

**Comment by akamming** [comment]
I stopped using this tool (bit apparently still i am scribed to this issue), so for me debugging is notmpossible

But a tip: ai is your friend: I am also no script buddy, bit lately when something on my pi doesn’t work, i just copy the code to chatgpt, then i copy the thing I want to debug and ask for a solution. 9 out of 10 times it shows me the correct solution

**Comment by harrykausl** [comment]
Are there any news about homebridge 2.0 integration of the homebridge-edomatics plugin.

**Comment by vespino** [comment]
@harrykausl no, it’s been quite ever since the last update. I’ve posted what my problem is above, but I don’t know how to solve this. If I could, I’d gladly fork the project so it can live on.

**Comment by vespino** [comment]
@akamming that does seem to work. Will you be submitting the change of forking the project?

**Comment by akamming** [comment]
Nice, since you have your own fork now, alternatieven you could create your own package.

Instructions are here: https://github.com/homebridge/homebridge-plugin-template

(If i’m correct you can skip the Build: I think edomoticz is coded directly in typescript

**Comment by madcat-nl** [comment]
What is the status of making this plugin homebridge 2.0 compatible?
currently this is the only plugin I use that is not compatible

**Comment by PatchworkBoy** [comment]
Last confirmed working with 2.0 beta 29 - no-one's mentioned any other issues since.

**Comment by madcat-nl** [comment]
Okey are there any steps left to mark it as Homebridge v2 compatible?

Edit: 
with version v2.1.50 i updated to v2.0.0-beta.29 and it worked

Only got some warnings, but those are probably due to a _ in the name
 
HAP-NodeJS WARNING: The accessory 'Tuin deur device_temperature' has an invalid 'Name' characteristic ('Tuin deur device_temperature'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.

**Comment by PatchworkBoy** [comment]
Wrapped up by https://github.com/PatchworkBoy/homebridge-edomoticz/pull/297
