### ISSUE TITLE
TypeError on start-up

### ISSUE THREAD

**Issue by AbsolutK** [PatchworkBoy/homebridge-edomoticz#67]
Hi since the last update I did yesterday of both homebridge and edomoticz I have below error on start-up:
...
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[12/17/2016, 8:29:27 AM] Loaded plugin: homebridge-edomoticz
[12/17/2016, 8:29:27 AM] Registering accessory 'homebridge-edomoticz.eDomoticz'
[12/17/2016, 8:29:27 AM] Registering platform 'homebridge-edomoticz.eDomoticz'
[12/17/2016, 8:29:27 AM] ---
[12/17/2016, 8:29:27 AM] Loaded config.json with 0 accessories and 1 platforms.
[12/17/2016, 8:29:27 AM] ---
[12/17/2016, 8:29:27 AM] Loading 1 platforms...
[12/17/2016, 8:29:27 AM] [Domoticz] Initializing eDomoticz platform...
[12/17/2016, 8:29:27 AM] Loading 0 accessories...
...
[12/17/2016, 8:29:28 AM] [Domoticz] Initializing platform accessory 'Eetkamer CO2'...
/usr/lib/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:1188
					airQualityService.getCharacteristic(Characteristic.AirParticulateDensity).on('get', this.getValue.bind(this));
					                                                                         ^

TypeError: Cannot read property 'on' of undefined
    at Object.eDomoticzAccessory.getServices (/usr/lib/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:1188:79)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:364:32)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-edomoticz/index.js:197:7)
    at Request._callback (/usr/lib/node_modules/homebridge-edomoticz/lib/domoticz.js:78:9)
    at Request.self.callback (/usr/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:1082:10)

**Comment by AbsolutK** [comment]
Update:
I'm running the latest stable version and this was originally the 4xxx SD image of Domoticz I'm using so homebridge is already integrated.

I used these commands to update:
sudo npm update -g homebridge --unsafe-perm
sudo npm update -g homebridge-edomoticz --unsafe-perm

**Comment by xTheRamon** [comment]
Excuse me for the late reply.

I have just resolved this issue in the latest commit.

Can you please update to the latest version (git or through npm) and let me know if the issue is resolved?

Thank you!

**Comment by xTheRamon** [comment]
Issue has been confirmed resolved!
