### ISSUE TITLE
node 8.0.0 and last homebridge - mqtt dont work

### ISSUE THREAD

**Issue by uronito** [PatchworkBoy/homebridge-edomoticz#83]
With node 8.0.0 and last homebridge mqtt updates dont work

**Comment by xTheRamon** [comment]
Hi @uronito,

Are you receiving the below error?
```
.../homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: The module '.../homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.../homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

The fix is quite simple: try executing a `npm rebuild` in the homebridge folder. If that does not work, try a `npm install`.

**Comment by xTheRamon** [comment]
This issue was related to the keepAliveTimeout setting being changed in the newest NodeJS versions.

I can confirm this issue is now resolved. To resolve, update the modules to the latest version in the homebridge directory.

https://github.com/nodejs/node/issues/13391
