### ISSUE TITLE
Error on start-up

### ISSUE THREAD

**Issue by Cavas17** [PatchworkBoy/homebridge-edomoticz#92]
Hi,

Since I update to the last version, homebridge can't start : 

[2017-7-21 15:19:46] [eDomoticz] Initializing eDomoticz platform...
/usr/local/lib/node_modules/homebridge-edomoticz/lib/helper.js:109
    e = Base64._utf8_encode(e);
        ^

ReferenceError: Base64 is not defined
    at Object.encode (/usr/local/lib/node_modules/homebridge-edomoticz/lib/helper.js:109:9)
    at eDomoticzPlatform (/usr/local/lib/node_modules/homebridge-edomoticz/index.js:100:45)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]

Any idea ?

Thanks

**Comment by xTheRamon** [comment]
Hi there!

Whoops, I made a small typo! Please update to the latest version (2.0.8) in npm and you'll see the issue is resolved.

**Comment by Cavas17** [comment]
Great !

Thanks a lot !
